### ISSUE TITLE
请问启动页是怎么关闭呢？

### ISSUE THREAD

**Issue by xifumengmengda** [h406621397/NeteaseNews#5]
我不想要启动页这个功能直接显示空白。我没看到你在项目中使用启动页，但是看到了关闭启动页的代码。

**Comment by h406621397** [comment]
启动页没效果么？？？  启动页是修改了一些原生android的文件配置的，不是在JS代码里面改的。你可以看我的commit记录，有一个就是"添加了启动页"，你可以看到我修改了哪些android文件。
